"""Add tax and shipping rates to business settings

Revision ID: 076025230813
Revises: 80d152eb3365
Create Date: 2026-04-21 18:01:25.879676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076025230813'
down_revision: Union[str, Sequence[str], None] = '80d152eb3365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('business_settings', sa.Column('shipping_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE business_settings SET tax_rate = 18.0, shipping_rate = 15.0")
    
    # Make columns non-nullable
    op.alter_column('business_settings', 'tax_rate', nullable=False)
    op.alter_column('business_settings', 'shipping_rate', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_settings', 'shipping_rate')
    op.drop_column('business_settings', 'tax_rate')
    # ### end Alembic commands ###
