"""rename quantity to quantity_kg

Revision ID: 6244c0e5a2f7
Revises: 035a6f2ef80a
Create Date: 2026-04-14 13:42:46.744687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6244c0e5a2f7'
down_revision: Union[str, Sequence[str], None] = '035a6f2ef80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'quantity_kg')
    # ### end Alembic commands ###
