"""Add address and city to customers

Revision ID: b5d8a6193b2d
Revises: 076025230813
Create Date: 2026-04-21 21:25:30.645691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d8a6193b2d'
down_revision: Union[str, Sequence[str], None] = '076025230813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_address', sa.String(length=512), nullable=True))
    op.add_column('customers', sa.Column('customer_city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'customer_city')
    op.drop_column('customers', 'customer_address')
    # ### end Alembic commands ###
